[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[package]
tournament = "programs/tournament"

[programs.localnet]
tournament = "BSA4cRmwYsbuCcRcmgSrhN51iBJgLBB5QdTK2kpqTDor"

[programs.devnet]
tournament = "BSA4cRmwYsbuCcRcmgSrhN51iBJgLBB5QdTK2kpqTDor"

[programs.mainnet]
tournament = "BSA4cRmwYsbuCcRcmgSrhN51iBJgLBB5QdTK2kpqTDor"

[registry]
url = "https://api.apr.dev"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/tournament"]
